import type { Company } from "../types/company";
import type { CompanyVariable, CompoundTable } from "../types/variable";
import type { TemplateStats } from "../types/template";
import type { PricingRules } from "../types/pricing";
import type { InboundLeadSimulation } from "../types/proposal";
import type { ProposalReceipt } from "../types/receipt";

export interface CompanyMockPackage {
  company: Company;
  variables: CompanyVariable[];
  compoundTables: CompoundTable[];
  templateStats: TemplateStats;
  pricingRules: PricingRules;
  leadSimulation: InboundLeadSimulation;
  receipt: ProposalReceipt;
}

export const MOCK_COMPANIES_DATA: Record<string, CompanyMockPackage> = {
  co1_seo: {
    company: {
      company_id: "co1_seo",
      company_name: "Northstar Digital",
      location: "Austin, TX",
      industry: "Digital Marketing / SEO Agency",
      email: "hello@northstardigital.io",
      website: "www.northstardigital.io",
      phone: "(512) 555-0148",
      briefing_locked: true,
      created_at: "2026-03-01T00:00:00Z",
      updated_at: "2026-03-01T00:00:00Z",
      working_state: null,
      pricing_spec: `We have 3 packages. Local is $1000/mo, for one location - GBP cleanup, on page stuff, one blog post a month. Growth is $3000/mo, up to 3 locations, more content (4 posts/mo), citations. Authority is $8000/mo, unlimited locations, dedicated strategist, weekly content - mostly our franchise clients end up here. For Austin/Texas clients we add sales tax, around 8.25%, bookkeeper has the exact number. Also do 10% off if someone pays annually upfront instead of monthly, always forget to put that down but we do offer it.`,
      document_metadata: {
        filename: "Co1_Proposal_Northstar_BloomAndCo.docx",
        filesize: 48200,
        parsed_at: "2026-09-07T14:30:00Z",
        extracted_markdown: `# Proposal for Bloom & Co Dental Group\n\n**Prepared by:** Northstar Digital (Austin, TX)\n**Date:** September 7, 2026\n**Valid until:** September 21, 2026 (14 days)\n\n## Selected Package: Growth ($3,000/mo)\n- Location Cap: Up to 3 physical clinics\n- Base Annual Investment: $36,000.00\n- 10% Annual Prepayment Discount: -$3,600.00\n- Subtotal: $32,400.00\n- Texas Sales Tax (8.25%): $2,673.00\n- **Grand Total: $35,073.00**`,
      },
      data: {
        company_id: "co1_seo",
        company_basics: {
          company_name: "Northstar Digital",
          location: "Austin, TX",
          email: "hello@northstardigital.io",
          phone: "(512) 555-0148",
          website: "www.northstardigital.io",
        },
        company_details: {
          industry: "Digital Marketing / SEO Agency",
          value_proposition: "We get local and multi-location service businesses found on Google before competitors.",
        },
        pricing_engine_spec: {
          pricing_context: "Digital Marketing tier-based monthly retainer with annual prepay discount and Texas sales tax.",
        },
      },
    },
    variables: [
      { id: "v1", company_id: "co1_seo", variable_name: "client_name", natural_name: "Client Name", category: "customer_input", data_type: "string", is_custom: false, is_deleted: false, sort_order: 1, created_at: "2026-03-01T00:00:00Z", updated_at: "2026-03-01T00:00:00Z", descriptor: { sample_value: "Bloom & Co Dental Group" } },
      { id: "v2", company_id: "co1_seo", variable_name: "location_count", natural_name: "Clinic Locations", category: "customer_input", data_type: "number", is_custom: false, is_deleted: false, sort_order: 2, created_at: "2026-03-01T00:00:00Z", updated_at: "2026-03-01T00:00:00Z", descriptor: { sample_value: "2" } },
      { id: "v3", company_id: "co1_seo", variable_name: "client_state", natural_name: "Client State", category: "customer_input", data_type: "string", is_custom: false, is_deleted: false, sort_order: 3, created_at: "2026-03-01T00:00:00Z", updated_at: "2026-03-01T00:00:00Z", descriptor: { sample_value: "TX" } },
      { id: "v4", company_id: "co1_seo", variable_name: "contact_email", natural_name: "Contact Email", category: "customer_input", data_type: "string", is_custom: false, is_deleted: false, sort_order: 4, created_at: "2026-03-01T00:00:00Z", updated_at: "2026-03-01T00:00:00Z", descriptor: { sample_value: "hello@bloom.co" } },
      { id: "v5", company_id: "co1_seo", variable_name: "selected_tier", natural_name: "Selected Tier", category: "pricing", data_type: "enum", is_custom: false, is_deleted: false, sort_order: 5, created_at: "2026-03-01T00:00:00Z", updated_at: "2026-03-01T00:00:00Z", descriptor: { sample_value: "Growth", enum_options: ["Local", "Growth", "Authority"] } },
      { id: "v6", company_id: "co1_seo", variable_name: "selected_tier_rate", natural_name: "Monthly Rate", category: "pricing", data_type: "currency", is_custom: false, is_deleted: false, sort_order: 6, created_at: "2026-03-01T00:00:00Z", updated_at: "2026-03-01T00:00:00Z", descriptor: { sample_value: "$3,000/mo" } },
      { id: "v7", company_id: "co1_seo", variable_name: "base_investment_amount", natural_name: "Annual Base Investment", category: "pricing", data_type: "currency", is_custom: false, is_deleted: false, sort_order: 7, created_at: "2026-03-01T00:00:00Z", updated_at: "2026-03-01T00:00:00Z", descriptor: { sample_value: "$36,000.00" } },
      { id: "v8", company_id: "co1_seo", variable_name: "annual_discount_amount", natural_name: "Annual Prepay Discount", category: "pricing", data_type: "currency", is_custom: false, is_deleted: false, sort_order: 8, created_at: "2026-03-01T00:00:00Z", updated_at: "2026-03-01T00:00:00Z", descriptor: { sample_value: "$3,600.00", visibility_rule: { condition_flag: "has_annual_discount" } } },
      { id: "v9", company_id: "co1_seo", variable_name: "subtotal_amount", natural_name: "Taxable Subtotal", category: "pricing", data_type: "currency", is_custom: false, is_deleted: false, sort_order: 9, created_at: "2026-03-01T00:00:00Z", updated_at: "2026-03-01T00:00:00Z", descriptor: { sample_value: "$32,400.00" } },
      { id: "v10", company_id: "co1_seo", variable_name: "tax_amount", natural_name: "Texas Sales Tax (8.25%)", category: "pricing", data_type: "currency", is_custom: false, is_deleted: false, sort_order: 10, created_at: "2026-03-01T00:00:00Z", updated_at: "2026-03-01T00:00:00Z", descriptor: { sample_value: "$2,673.00", visibility_rule: { condition_flag: "has_tax" } } },
      { id: "v11", company_id: "co1_seo", variable_name: "total_investment_amount", natural_name: "Grand Total", category: "pricing", data_type: "currency", is_custom: false, is_deleted: false, sort_order: 11, created_at: "2026-03-01T00:00:00Z", updated_at: "2026-03-01T00:00:00Z", descriptor: { sample_value: "$35,073.00" } },
      { id: "v12", company_id: "co1_seo", variable_name: "client_current_situation_narrative", natural_name: "Executive Overview", category: "paragraph", data_type: "paragraph", is_custom: false, is_deleted: false, sort_order: 12, created_at: "2026-03-01T00:00:00Z", updated_at: "2026-03-01T00:00:00Z", descriptor: { sample_value: "Thanks for reaching out — you mentioned Bloom & Co now has two active clinic locations in Austin and isn't showing up on Google Maps. Single-location SEO stops working once a second location enters the picture.", paragraph_config: { mode: "ai_generated", purpose: "Executive overview tailored to multi-location dental practice." } } },
      { id: "v13", company_id: "co1_seo", variable_name: "scope_inclusions_narrative", natural_name: "Custom Deliverables", category: "paragraph", data_type: "paragraph", is_custom: false, is_deleted: false, sort_order: 13, created_at: "2026-03-01T00:00:00Z", updated_at: "2026-03-01T00:00:00Z", descriptor: { sample_value: "Included: Google Business Profile management for both clinic locations\nIncluded: On-page SEO across your site, citation building across major directories\nIncluded: 4 content pieces/month, quarterly strategy call, monthly performance report", paragraph_config: { mode: "fixed", purpose: "Scope inclusions" } } },
    ],
    compoundTables: [],
    templateStats: {
      template_path: "templates/co1_seo_hydrated.docx",
      tags_placed_count: 18,
      loops_collapsed_count: 0,
      conditional_rows_wrapped_count: 2,
      mutations_applied_count: 20,
      tier_matrix: {
        selector: "selected_tier",
        recommended_index: 1,
        tiers: [
          { name: "Local", cells: ["1 Location", "1 Post / Mo", "$1,000/mo"] },
          { name: "Growth", cells: ["3 Locations", "4 Posts / Mo", "$3,000/mo"] },
          { name: "Authority", cells: ["Unlimited", "Weekly Posts", "$8,000/mo"] },
        ],
      },
      details: [
        { action: "place_tag", target: "selected_tier", applied: true, info: "Matched 1 occurrence" },
        { action: "conditional_row", target: "annual_discount_amount", applied: true, info: "Wrapped in conditional row {#has_annual_discount}" },
        { action: "conditional_row", target: "tax_amount", applied: true, info: "Wrapped in conditional row {#has_tax}" },
      ],
    },
    pricingRules: {
      version: 1,
      tables: [
        {
          id: "packages",
          label: "Packages",
          kind: "packages",
          columns: [
            { key: "name", label: "Package", unit: "text" },
            { key: "monthly_rate", label: "Monthly rate", unit: "money" },
            { key: "location_cap", label: "Location cap", unit: "integer" },
          ],
          rows: [
            { name: "Local", monthly_rate: 1000, location_cap: 1 },
            { name: "Growth", monthly_rate: 3000, location_cap: 3 },
            { name: "Authority", monthly_rate: 8000, location_cap: null },
          ],
        },
        {
          id: "taxes",
          label: "Sales tax",
          kind: "taxes",
          columns: [
            { key: "state", label: "State", unit: "text" },
            { key: "state_name", label: "Jurisdiction", unit: "text" },
            { key: "rate", label: "Rate", unit: "percent" },
          ],
          rows: [{ state: "TX", state_name: "Texas", rate: 0.0825 }],
        },
      ],
      variables: [
        { name: "location_count", label: "Number of locations", in_document: false, unit: "integer", condition_flag: "", kind: "input", input_type: "integer", required: true },
        { name: "client_state", label: "Client state", in_document: false, unit: "text", condition_flag: "", kind: "input", input_type: "us_state", required: true },
        { name: "annual_prepay", label: "Pays annually up front", in_document: false, unit: "boolean", condition_flag: "", kind: "input", input_type: "boolean", required: false },
        { name: "selected_tier", label: "Selected package", in_document: true, unit: "text", condition_flag: "", kind: "lookup", table: "packages", where: [{ column: "location_cap", op: "gte", value_var: "location_count" }], take: "name" },
        { name: "selected_tier_rate", label: "Package monthly rate", in_document: true, unit: "money", condition_flag: "", kind: "lookup", table: "packages", where: [{ column: "name", op: "eq", value_var: "selected_tier" }], take: "monthly_rate" },
        { name: "contract_months", label: "Contract length (months)", in_document: true, unit: "integer", condition_flag: "", kind: "constant", value: 12 },
        { name: "base_investment_amount", label: "Base investment", in_document: true, unit: "money", condition_flag: "", kind: "formula", op: "mul", args: ["selected_tier_rate", "contract_months"] },
        { name: "annual_discount_percentage", label: "Annual prepay discount", in_document: true, unit: "percent", condition_flag: "", kind: "constant", value: 0.1 },
        { name: "has_annual_discount", label: "Annual discount applies", in_document: false, unit: "boolean", condition_flag: "", kind: "condition", all: [{ var: "annual_prepay", op: "eq", value: true }] },
        { name: "annual_discount_amount", label: "Annual discount", in_document: true, unit: "money", condition_flag: "has_annual_discount", kind: "formula", op: "mul", args: ["base_investment_amount", "annual_discount_percentage"] },
        { name: "subtotal_amount", label: "Subtotal", in_document: true, unit: "money", condition_flag: "", kind: "formula", op: "sub", args: ["base_investment_amount", "annual_discount_amount"] },
        { name: "tax_match_count", label: "Tax rows for the client's state", in_document: false, unit: "integer", condition_flag: "", kind: "aggregate", fn: "count", table: "taxes", rows: "all", key_column: "state", where: [{ column: "state", op: "eq", value_var: "client_state" }] },
        { name: "has_tax", label: "Sales tax applies", in_document: false, unit: "boolean", condition_flag: "", kind: "condition", all: [{ var: "tax_match_count", op: "gt", value: 0 }] },
        { name: "tax_jurisdiction", label: "Tax jurisdiction", in_document: true, unit: "text", condition_flag: "has_tax", kind: "lookup", table: "taxes", where: [{ column: "state", op: "eq", value_var: "client_state" }], take: "state_name" },
        { name: "tax_rate", label: "Tax rate", in_document: true, unit: "percent", condition_flag: "has_tax", kind: "lookup", table: "taxes", where: [{ column: "state", op: "eq", value_var: "client_state" }], take: "rate" },
        { name: "tax_amount", label: "Sales tax", in_document: true, unit: "money", condition_flag: "has_tax", kind: "formula", op: "mul", args: ["subtotal_amount", "tax_rate"] },
        { name: "total_investment_amount", label: "Total investment", in_document: true, unit: "money", condition_flag: "", kind: "formula", op: "add", args: ["subtotal_amount", "tax_amount"] },
      ],
      review_rules: [],
      assumptions: [
        { text: 'Owner notes say tax is "around 8.25%" without a basis.', resolved_as: "Texas sales tax at 8.25% on the post-discount subtotal." },
        { text: "Monthly (non-prepay) leads are not priced in the notes.", resolved_as: "Quoted as 12 months at the monthly rate with the discount row hidden." },
      ],
      sample_inputs: { location_count: 2, client_state: "TX", annual_prepay: true },
    },
    leadSimulation: {
      lead_id: "lead_bloom_01",
      source: "whatsapp",
      received_at: "Sept 4, 2026, 2:15 PM CT",
      sender_name: "Dr. Sarah Bloom",
      sender_title: "Managing Partner",
      sender_company: "Bloom & Co Dental Group",
      raw_message: "Hi, saw your message about local SEO. We're Bloom & Co, a dental group — we actually have two clinic locations now in the Austin area and neither shows up on Google when people search near either one. What would it cost to fix that? Also, would rather just pay once a year if that gets us a better rate than monthly.",
      extracted_params: {
        locations: 2,
        tier_requested: "Growth",
        is_annual_prepay: true,
        client_state: "TX",
      },
      tailored_sales_copy: {
        executive_overview: "Thanks for reaching out through our outreach campaign — you mentioned Bloom & Co now has two active clinic locations in Austin and isn't showing up when local patients search on Google. Single-location SEO tactics stop working once a second location enters the picture. Below is the Growth plan tailored to cover both your Austin clinics under one unified program.",
        deliverables_scope: "• Full Google Business Profile optimization & citation cleanup across both Austin clinics\n• Technical on-page SEO repairs and keyword clustering for dental search terms\n• 4 targeted local content articles per month with review acquisition strategy\n• Monthly transparent ranking and ROI conversion report",
        guarantee_and_sla: "Month-to-month after the initial 3-month setup window. Guaranteed keyword rank improvement by month 4 or we perform a free complete strategy reset.",
      },
    },
    receipt: {
      receipt_id: "REC-NSD-2026-0814",
      proposal_id: "PROP-NSD-8891",
      date_issued: "September 7, 2026",
      valid_until: "September 21, 2026",
      status: "verified",
      company: {
        name: "Northstar Digital",
        location: "Austin, TX",
        email: "hello@northstardigital.io",
        phone: "(512) 555-0148",
      },
      client: {
        name: "Dr. Sarah Bloom",
        company: "Bloom & Co Dental Group",
        location: "Austin, TX",
        email: "hello@bloom.co",
      },
      deal_summary: {
        tier_name: "Growth Package",
        locations_count: 2,
        payment_terms: "Annual Prepayment (10% Discount Applied)",
      },
      line_items: [
        { id: "li_1", label: "Growth SEO Package (12 Months × $3,000.00/mo)", amount: 36000, type: "package" },
        { id: "li_2", label: "Annual Prepayment Discount (10% off Annual)", amount: -3600, type: "discount", isDiscount: true },
        { id: "li_3", label: "Texas State Sales Tax (8.25% on Post-Discount Subtotal)", amount: 2673, type: "tax", isTax: true },
      ],
      financials: {
        base_subtotal: 36000,
        discounts_total: 3600,
        taxable_subtotal: 32400,
        tax_rate: 0.0825,
        tax_amount: 2673,
        grand_total: 35073,
        formatted_grand_total: "$35,073.00",
      },
      governing_rules: [
        "Package tier matched by location cap (2 locations ≤ Growth 3-location cap)",
        "Annual discount applied to full 12-month base investment",
        "Texas sales tax computed on post-discount taxable subtotal ($32,400.00 × 8.25%)",
      ],
    },
  },

  co2_msp: {
    company: {
      company_id: "co2_msp",
      company_name: "Fortress IT Group",
      location: "Columbus, OH",
      industry: "IT Managed Service Provider (MSP)",
      email: "sales@fortressitgroup.com",
      website: "www.fortressitgroup.com",
      phone: "(614) 555-0193",
      briefing_locked: true,
      created_at: "2026-03-01T00:00:00Z",
      updated_at: "2026-03-01T00:00:00Z",
      working_state: null,
      pricing_spec: `Pricing is per seat per month based on support tier. Essential $45/seat/mo - basic helpdesk, patching, monitoring, business hours only. Standard $65/seat/mo - faster SLA, backup management, after hours emergency line. Premium $85/seat/mo - vCIO quarterly review, 24/7 support, priority response under 1hr. Once a client crosses 25 total seats it's $5/seat off whatever tier rate, and past 50 seats it's $10/seat off instead (not stacked, just whichever band they're in). Devices beyond a 1:1 ratio with seats - servers, shared workstations, kiosks - billed separately at $12/device/mo regardless of tier. One time onboarding fee of $75 per seat. 10 seat minimum commit (billed for 10 even if fewer, though we don't really take on anyone smaller than that anyway). Tax is flat 6% Ohio rate for home state clients, applied to the recurring monthly total, not the setup fee.`,
      document_metadata: {
        filename: "Co2_Proposal_FortressIT_WhitfieldAssociates.docx",
        filesize: 51200,
        parsed_at: "2026-09-07T14:30:00Z",
        extracted_markdown: `# Proposal for Whitfield & Associates\n\n**Prepared by:** Fortress IT Group (Columbus, OH)\n**Date:** September 7, 2026\n\n- Support Tier: Standard ($65 base - $5 volume discount = $60.00/seat/mo)\n- Seat Subtotal (42 seats × $60.00): $2,520.00/mo\n- Managed Devices (5 extra × $12.00): $60.00/mo\n- Recurring Subtotal: $2,580.00/mo\n- Ohio Sales Tax (6.00%): $154.80/mo\n- **Total Monthly Recurring: $2,734.80/mo**\n- **One-Time Onboarding Fee (42 seats × $75.00): $3,150.00 (Untaxed)**`,
      },
      data: {
        company_id: "co2_msp",
        company_basics: {
          company_name: "Fortress IT Group",
          location: "Columbus, OH",
          email: "sales@fortressitgroup.com",
          phone: "(614) 555-0193",
          website: "www.fortressitgroup.com",
        },
        company_details: {
          industry: "IT Managed Service Provider (MSP)",
          value_proposition: "Flat-rate, predictable IT support for 10-250 employee professional service firms.",
        },
        pricing_engine_spec: {
          pricing_context: "Per-seat IT managed support tiers with volume discounts, device add-ons, onboarding fee, and Ohio tax.",
        },
      },
    },
    variables: [
      { id: "v201", company_id: "co2_msp", variable_name: "client_name", natural_name: "Client Name", category: "customer_input", data_type: "string", is_custom: false, is_deleted: false, sort_order: 1, created_at: "2026-03-01T00:00:00Z", updated_at: "2026-03-01T00:00:00Z", descriptor: { sample_value: "Whitfield & Associates" } },
      { id: "v202", company_id: "co2_msp", variable_name: "seat_count", natural_name: "Employee Seats", category: "customer_input", data_type: "number", is_custom: false, is_deleted: false, sort_order: 2, created_at: "2026-03-01T00:00:00Z", updated_at: "2026-03-01T00:00:00Z", descriptor: { sample_value: "42" } },
      { id: "v203", company_id: "co2_msp", variable_name: "selected_tier", natural_name: "Support Tier", category: "customer_input", data_type: "enum", is_custom: false, is_deleted: false, sort_order: 3, created_at: "2026-03-01T00:00:00Z", updated_at: "2026-03-01T00:00:00Z", descriptor: { sample_value: "Standard", enum_options: ["Essential", "Standard", "Premium"] } },
      { id: "v204", company_id: "co2_msp", variable_name: "extra_device_count", natural_name: "Extra Managed Devices", category: "customer_input", data_type: "number", is_custom: false, is_deleted: false, sort_order: 4, created_at: "2026-03-01T00:00:00Z", updated_at: "2026-03-01T00:00:00Z", descriptor: { sample_value: "5" } },
      { id: "v205", company_id: "co2_msp", variable_name: "client_state", natural_name: "Client State", category: "customer_input", data_type: "string", is_custom: false, is_deleted: false, sort_order: 5, created_at: "2026-03-01T00:00:00Z", updated_at: "2026-03-01T00:00:00Z", descriptor: { sample_value: "OH" } },
      { id: "v206", company_id: "co2_msp", variable_name: "adjusted_seat_rate", natural_name: "Adjusted Seat Rate", category: "pricing", data_type: "currency", is_custom: false, is_deleted: false, sort_order: 6, created_at: "2026-03-01T00:00:00Z", updated_at: "2026-03-01T00:00:00Z", descriptor: { sample_value: "$60.00/seat/mo" } },
      { id: "v207", company_id: "co2_msp", variable_name: "seat_subtotal", natural_name: "Seat Subtotal", category: "pricing", data_type: "currency", is_custom: false, is_deleted: false, sort_order: 7, created_at: "2026-03-01T00:00:00Z", updated_at: "2026-03-01T00:00:00Z", descriptor: { sample_value: "$2,520.00" } },
      { id: "v208", company_id: "co2_msp", variable_name: "extra_device_subtotal", natural_name: "Device Add-on Subtotal", category: "pricing", data_type: "currency", is_custom: false, is_deleted: false, sort_order: 8, created_at: "2026-03-01T00:00:00Z", updated_at: "2026-03-01T00:00:00Z", descriptor: { sample_value: "$60.00", visibility_rule: { condition_flag: "has_extra_devices" } } },
      { id: "v209", company_id: "co2_msp", variable_name: "total_monthly_recurring", natural_name: "Total Monthly Recurring", category: "pricing", data_type: "currency", is_custom: false, is_deleted: false, sort_order: 9, created_at: "2026-03-01T00:00:00Z", updated_at: "2026-03-01T00:00:00Z", descriptor: { sample_value: "$2,734.80/mo" } },
      { id: "v210", company_id: "co2_msp", variable_name: "setup_fee_total", natural_name: "One-Time Setup Fee", category: "pricing", data_type: "currency", is_custom: false, is_deleted: false, sort_order: 10, created_at: "2026-03-01T00:00:00Z", updated_at: "2026-03-01T00:00:00Z", descriptor: { sample_value: "$3,150.00" } },
    ],
    compoundTables: [],
    templateStats: {
      template_path: "templates/co2_msp_hydrated.docx",
      tags_placed_count: 21,
      loops_collapsed_count: 0,
      conditional_rows_wrapped_count: 3,
      mutations_applied_count: 24,
      details: [
        { action: "place_tag", target: "adjusted_seat_rate", applied: true, info: "Applied from Standard tier minus 25-49 seat breakpoint" },
        { action: "place_tag", target: "setup_fee_total", applied: true, info: "Untaxed one-time fee row" },
      ],
    },
    pricingRules: {
      version: 1,
      tables: [
        {
          id: "tiers",
          label: "Support Tiers",
          kind: "packages",
          columns: [
            { key: "name", label: "Tier", unit: "text" },
            { key: "rate_per_seat", label: "Rate / Seat", unit: "money" },
            { key: "sla", label: "SLA Response", unit: "text" },
          ],
          rows: [
            { name: "Essential", rate_per_seat: 45, sla: "Business hours only (4hr SLA)" },
            { name: "Standard", rate_per_seat: 65, sla: "Faster SLA + emergency backup" },
            { name: "Premium", rate_per_seat: 85, sla: "24/7 Priority < 1hr + vCIO" },
          ],
        },
        {
          id: "volume_bands",
          label: "Volume Breakpoints",
          kind: "bands",
          columns: [
            { key: "min_seats", label: "Min Seats", unit: "integer" },
            { key: "max_seats", label: "Max Seats", unit: "integer" },
            { key: "discount_per_seat", label: "Discount / Seat", unit: "money" },
            { key: "label", label: "Band Name", unit: "text" },
          ],
          rows: [
            { min_seats: 0, max_seats: 24, discount_per_seat: 0, label: "1–24 seat baseline" },
            { min_seats: 25, max_seats: 49, discount_per_seat: 5, label: "25–49 seat band" },
            { min_seats: 50, max_seats: null, discount_per_seat: 10, label: "50+ seat band" },
          ],
        },
        {
          id: "taxes",
          label: "State Sales Tax",
          kind: "taxes",
          columns: [
            { key: "state", label: "State", unit: "text" },
            { key: "rate", label: "Rate", unit: "percent" },
          ],
          rows: [{ state: "OH", rate: 0.06 }],
        },
      ],
      variables: [
        { name: "seat_count", label: "Employee seats", in_document: false, unit: "integer", condition_flag: "", kind: "input", input_type: "integer", required: true },
        { name: "selected_tier", label: "Chosen support tier", in_document: false, unit: "text", condition_flag: "", kind: "input", input_type: "choice", required: true, options: ["Essential", "Standard", "Premium"] },
        { name: "extra_device_count", label: "Devices beyond 1:1", in_document: false, unit: "integer", condition_flag: "", kind: "input", input_type: "integer", required: false },
        { name: "client_state", label: "Client state", in_document: false, unit: "text", condition_flag: "", kind: "input", input_type: "us_state", required: true },
        { name: "minimum_seat_commitment", label: "Floor seats", in_document: false, unit: "integer", condition_flag: "", kind: "constant", value: 10 },
        { name: "billed_seat_count", label: "Billed seats", in_document: false, unit: "integer", condition_flag: "", kind: "formula", op: "max", args: ["seat_count", "minimum_seat_commitment"] },
        { name: "base_rate_per_seat", label: "Base rate", in_document: true, unit: "money", condition_flag: "", kind: "lookup", table: "tiers", where: [{ column: "name", op: "eq", value_var: "selected_tier" }], take: "rate_per_seat" },
        { name: "volume_discount_per_seat", label: "Volume discount", in_document: true, unit: "money", condition_flag: "", kind: "lookup", table: "volume_bands", where: [{ column: "min_seats", op: "lte", value_var: "billed_seat_count" }, { column: "max_seats", op: "gte", value_var: "billed_seat_count" }], take: "discount_per_seat" },
        { name: "adjusted_seat_rate", label: "Adjusted seat rate", in_document: true, unit: "money", condition_flag: "", kind: "formula", op: "sub", args: ["base_rate_per_seat", "volume_discount_per_seat"] },
        { name: "seat_subtotal", label: "Seat subtotal", in_document: true, unit: "money", condition_flag: "", kind: "formula", op: "mul", args: ["billed_seat_count", "adjusted_seat_rate"] },
        { name: "device_rate", label: "Device unit rate", in_document: true, unit: "money", condition_flag: "", kind: "constant", value: 12 },
        { name: "has_extra_devices", label: "Has extra devices", in_document: false, unit: "boolean", condition_flag: "", kind: "condition", all: [{ var: "extra_device_count", op: "gt", value: 0 }] },
        { name: "extra_device_subtotal", label: "Device add-on subtotal", in_document: true, unit: "money", condition_flag: "has_extra_devices", kind: "formula", op: "mul", args: ["extra_device_count", "device_rate"] },
        { name: "recurring_subtotal", label: "Recurring subtotal", in_document: true, unit: "money", condition_flag: "", kind: "formula", op: "add", args: ["seat_subtotal", "extra_device_subtotal"] },
        { name: "tax_match_count", label: "Ohio tax match", in_document: false, unit: "integer", condition_flag: "", kind: "aggregate", fn: "count", table: "taxes", rows: "all", key_column: "state", where: [{ column: "state", op: "eq", value_var: "client_state" }] },
        { name: "has_tax", label: "Sales tax applies", in_document: false, unit: "boolean", condition_flag: "", kind: "condition", all: [{ var: "tax_match_count", op: "gt", value: 0 }] },
        { name: "tax_rate", label: "Tax rate", in_document: true, unit: "percent", condition_flag: "has_tax", kind: "lookup", table: "taxes", where: [{ column: "state", op: "eq", value_var: "client_state" }], take: "rate" },
        { name: "monthly_tax_amount", label: "Ohio tax", in_document: true, unit: "money", condition_flag: "has_tax", kind: "formula", op: "mul", args: ["recurring_subtotal", "tax_rate"] },
        { name: "total_monthly_recurring", label: "Total monthly recurring", in_document: true, unit: "money", condition_flag: "", kind: "formula", op: "add", args: ["recurring_subtotal", "monthly_tax_amount"] },
        { name: "onboarding_unit_rate", label: "Onboarding per seat", in_document: true, unit: "money", condition_flag: "", kind: "constant", value: 75 },
        { name: "setup_fee_total", label: "One-time onboarding fee", in_document: true, unit: "money", condition_flag: "", kind: "formula", op: "mul", args: ["billed_seat_count", "onboarding_unit_rate"] },
      ],
      review_rules: [],
      assumptions: [
        { text: "Tax applies only to recurring MSP services, not onboarding.", resolved_as: "Ohio 6% tax computed on recurring monthly subtotal only ($2,580.00 × 6% = $154.80)." },
      ],
      sample_inputs: { seat_count: 42, selected_tier: "Standard", extra_device_count: 5, client_state: "OH" },
    },
    leadSimulation: {
      lead_id: "lead_whitfield_02",
      source: "email",
      received_at: "Sept 5, 2026, 9:44 AM ET",
      sender_name: "Arthur Whitfield",
      sender_title: "Managing Director",
      sender_company: "Whitfield & Associates",
      raw_message: "Hello Fortress team, our accounting firm is expanding — we're up to 42 staff members now across our Columbus office. We also have 5 dedicated local servers for our tax databases. Looking for standard business hours coverage plus after-hours emergency line for tax season deadlines. What would monthly support look like?",
      extracted_params: {
        seats: 42,
        tier_requested: "Standard",
        extra_devices: 5,
        client_state: "OH",
      },
      tailored_sales_copy: {
        executive_overview: "Whitfield & Associates operates a high-compliance accounting practice with 42 staff members and 5 on-premise tax database servers. Fortress IT Group will provide end-to-end Standard IT Management with guaranteed 2-hour SLA response and after-hours emergency support during peak tax deadlines.",
        deliverables_scope: "• Standard Helpdesk & Remote Monitoring for 42 employee seats\n• 5 Dedicated On-Premise Servers Maintained ($12.00/dev/mo)\n• 25-49 Seat Volume Discount Applied ($5.00/seat reduction)\n• Comprehensive Onboarding & Security Hardening ($75/seat)",
        guarantee_and_sla: "2-Hour SLA on high-priority tickets, 15-minute response on emergency after-hours tax season hotline.",
      },
    },
    receipt: {
      receipt_id: "REC-FIT-2026-0922",
      proposal_id: "PROP-FIT-9940",
      date_issued: "September 7, 2026",
      valid_until: "September 28, 2026",
      status: "verified",
      company: {
        name: "Fortress IT Group",
        location: "Columbus, OH",
        email: "sales@fortressitgroup.com",
        phone: "(614) 555-0193",
      },
      client: {
        name: "Arthur Whitfield",
        company: "Whitfield & Associates",
        location: "Columbus, OH",
        email: "arthur@whitfieldlaw.com",
      },
      deal_summary: {
        tier_name: "Standard MSP Support (42 Seats)",
        seats_count: 42,
        payment_terms: "Monthly Recurring + One-Time Onboarding",
      },
      line_items: [
        { id: "li_1", label: "Standard MSP Support Tier (42 Seats × $60.00/seat/mo)", amount: 2520, rateLabel: "Base $65.00 - $5.00 volume band", type: "package" },
        { id: "li_2", label: "Managed Database Servers Add-on (5 Servers × $12.00/mo)", amount: 60, type: "addon" },
        { id: "li_3", label: "Ohio State Sales Tax (6.00% Recurring)", amount: 154.8, type: "tax", isTax: true },
        { id: "li_4", label: "One-Time Setup & Security Onboarding (42 Seats × $75.00)", amount: 3150, type: "addon" },
      ],
      financials: {
        base_subtotal: 2580,
        discounts_total: 210,
        taxable_subtotal: 2580,
        tax_rate: 0.06,
        tax_amount: 154.8,
        grand_total: 5884.8,
        formatted_grand_total: "$2,734.80/mo + $3,150.00 Setup",
      },
      governing_rules: [
        "42 seats qualify for $5/seat volume discount ($65.00 → $60.00/seat)",
        "5 servers billed at flat $12.00/device/mo rate",
        "Ohio 6% tax applies only to recurring services ($2,580.00 × 6% = $154.80); setup fee untaxed",
      ],
    },
  },

  co3_dev: {
    company: {
      company_id: "co3_dev",
      company_name: "Fieldstone Studio",
      location: "Remote (US-based)",
      industry: "Web / Software Development Agency",
      email: "studio@fieldstonestudio.com",
      website: "www.fieldstonestudio.com",
      phone: "(800) 555-0182",
      briefing_locked: true,
      created_at: "2026-03-01T00:00:00Z",
      updated_at: "2026-03-01T00:00:00Z",
      working_state: null,
      pricing_spec: `Fixed-price website and e-commerce builds. Landing page $2,500. Business website $6,000. E-commerce build $9,500 (up to 100 products, 4-6 weeks). Custom web app starts at $22,000 (needs scoping call). Add-ons: Copywriting ($600), Basic SEO Setup ($450), CMS Integration ($800), Extra revision round ($300). If client picks 2 or more stackable add-ons, give 10% off the add-on subtotal. Default payment terms are 50% deposit upon kickoff and 50% upon final delivery. Tax is 0% resolved default.`,
      document_metadata: {
        filename: "Co3_Proposal_Fieldstone_RosewoodHomeGoods.docx",
        filesize: 45000,
        parsed_at: "2026-09-07T14:30:00Z",
        extracted_markdown: `# Proposal for Rosewood Home Goods\n\n**Prepared by:** Fieldstone Studio\n**Date:** September 7, 2026\n\n- Project Template: E-Commerce Build ($9,500.00)\n- Add-on: Copywriting ($600.00)\n- Add-on: Basic SEO Setup ($450.00)\n- Stackable Add-on Subtotal: $1,050.00\n- 10% Bundle Discount: -$105.00\n- Net Add-ons Total: $945.00\n- **Total Project Investment: $10,445.00**\n- Payment Split: 50% Deposit ($5,222.50) / 50% Launch ($5,222.50)`,
      },
      data: {
        company_id: "co3_dev",
        company_basics: {
          company_name: "Fieldstone Studio",
          location: "Remote (US-based)",
          email: "studio@fieldstonestudio.com",
          website: "www.fieldstonestudio.com",
          phone: "(800) 555-0182",
        },
        company_details: {
          industry: "Web / Software Development Agency",
          value_proposition: "Fixed-price, fixed-timeline websites and e-commerce builds for growing brands.",
        },
        pricing_engine_spec: {
          pricing_context: "Fixed price web development scopes with stackable add-on discounts and 50/50 milestone billing.",
        },
      },
    },
    variables: [
      { id: "v301", company_id: "co3_dev", variable_name: "client_name", natural_name: "Client Name", category: "customer_input", data_type: "string", is_custom: false, is_deleted: false, sort_order: 1, created_at: "2026-03-01T00:00:00Z", updated_at: "2026-03-01T00:00:00Z", descriptor: { sample_value: "Rosewood Home Goods" } },
      { id: "v302", company_id: "co3_dev", variable_name: "product_count", natural_name: "Product Catalog Count", category: "customer_input", data_type: "number", is_custom: false, is_deleted: false, sort_order: 2, created_at: "2026-03-01T00:00:00Z", updated_at: "2026-03-01T00:00:00Z", descriptor: { sample_value: "60" } },
      { id: "v303", company_id: "co3_dev", variable_name: "project_template_name", natural_name: "Selected Template", category: "customer_input", data_type: "enum", is_custom: false, is_deleted: false, sort_order: 3, created_at: "2026-03-01T00:00:00Z", updated_at: "2026-03-01T00:00:00Z", descriptor: { sample_value: "E-Commerce Build", enum_options: ["Landing Page", "Business Website", "E-Commerce Build", "Custom Web App"] } },
      { id: "v304", company_id: "co3_dev", variable_name: "base_template_fee", natural_name: "Base Template Fee", category: "pricing", data_type: "currency", is_custom: false, is_deleted: false, sort_order: 4, created_at: "2026-03-01T00:00:00Z", updated_at: "2026-03-01T00:00:00Z", descriptor: { sample_value: "$9,500.00" } },
      { id: "v305", company_id: "co3_dev", variable_name: "addon_subtotal", natural_name: "Add-ons Subtotal", category: "pricing", data_type: "currency", is_custom: false, is_deleted: false, sort_order: 5, created_at: "2026-03-01T00:00:00Z", updated_at: "2026-03-01T00:00:00Z", descriptor: { sample_value: "$1,050.00" } },
      { id: "v306", company_id: "co3_dev", variable_name: "bundle_discount_amount", natural_name: "10% Bundle Discount", category: "pricing", data_type: "currency", is_custom: false, is_deleted: false, sort_order: 6, created_at: "2026-03-01T00:00:00Z", updated_at: "2026-03-01T00:00:00Z", descriptor: { sample_value: "$105.00", visibility_rule: { condition_flag: "has_bundle_discount" } } },
      { id: "v307", company_id: "co3_dev", variable_name: "total_project_investment", natural_name: "Total Project Investment", category: "pricing", data_type: "currency", is_custom: false, is_deleted: false, sort_order: 7, created_at: "2026-03-01T00:00:00Z", updated_at: "2026-03-01T00:00:00Z", descriptor: { sample_value: "$10,445.00" } },
    ],
    compoundTables: [
      {
        id: "t1",
        table_id: "addons_tbl",
        type: "repeating_loop",
        loop_tag: "addon_items",
        natural_name: "Selected Add-ons Table",
        columns: ["addon_name", "addon_fee"],
        header_texts: ["Add-on Service", "Price"],
        row_labels: ["Copywriting ($600.00)", "Basic SEO Setup ($450.00)"],
        is_deleted: false,
      },
      {
        id: "t2",
        table_id: "splits_tbl",
        type: "repeating_loop",
        loop_tag: "payment_milestones",
        natural_name: "Payment Milestones (50/50)",
        columns: ["milestone_name", "payment_amount"],
        header_texts: ["Milestone", "Amount"],
        row_labels: ["50% Deposit ($5,222.50)", "50% Launch Payment ($5,222.50)"],
        is_deleted: false,
      },
    ],
    templateStats: {
      template_path: "templates/co3_dev_hydrated.docx",
      tags_placed_count: 17,
      loops_collapsed_count: 2,
      conditional_rows_wrapped_count: 1,
      mutations_applied_count: 20,
      details: [
        { action: "collapse_loop", target: "addon_items", applied: true, info: "Dynamic table loop {#addon_items}" },
        { action: "collapse_loop", target: "payment_milestones", applied: true, info: "Dynamic table loop {#payment_milestones}" },
      ],
    },
    pricingRules: {
      version: 1,
      tables: [
        {
          id: "templates",
          label: "Project Templates",
          kind: "packages",
          columns: [
            { key: "name", label: "Template", unit: "text" },
            { key: "fee", label: "Base Fee", unit: "money" },
            { key: "product_cap", label: "Product Cap", unit: "integer" },
          ],
          rows: [
            { name: "Landing Page", fee: 2500, product_cap: null },
            { name: "Business Website", fee: 6000, product_cap: null },
            { name: "E-Commerce Build", fee: 9500, product_cap: 100 },
            { name: "Custom Web App", fee: 22000, product_cap: null },
          ],
        },
        {
          id: "addons",
          label: "Available Add-ons",
          kind: "addons",
          columns: [
            { key: "name", label: "Add-on", unit: "text" },
            { key: "fee", label: "Fee", unit: "money" },
            { key: "stackable", label: "Stackable", unit: "boolean" },
          ],
          rows: [
            { name: "Copywriting", fee: 600, stackable: true },
            { name: "Basic SEO Setup", fee: 450, stackable: true },
            { name: "CMS Integration", fee: 800, stackable: true },
            { name: "Extra Revision Round", fee: 300, stackable: true },
          ],
        },
      ],
      variables: [
        { name: "product_count", label: "Product count", in_document: false, unit: "integer", condition_flag: "", kind: "input", input_type: "integer", required: true },
        { name: "project_template_name", label: "Chosen template", in_document: false, unit: "text", condition_flag: "", kind: "input", input_type: "choice", required: true, options: ["Landing Page", "Business Website", "E-Commerce Build", "Custom Web App"] },
        { name: "base_template_fee", label: "Base fee", in_document: true, unit: "money", condition_flag: "", kind: "lookup", table: "templates", where: [{ column: "name", op: "eq", value_var: "project_template_name" }], take: "fee" },
        { name: "addon_subtotal", label: "Add-on subtotal", in_document: true, unit: "money", condition_flag: "", kind: "constant", value: 1050 },
        { name: "bundle_discount_amount", label: "Bundle discount", in_document: true, unit: "money", condition_flag: "", kind: "constant", value: 105 },
        { name: "total_project_investment", label: "Total project investment", in_document: true, unit: "money", condition_flag: "", kind: "constant", value: 10445 },
      ],
      review_rules: [
        { when: [{ var: "product_count", op: "gt", value: 100 }], reason: "Product count exceeds 100-product cap of E-Commerce Build — scoping required." },
      ],
      assumptions: [
        { text: "Tax is 0% resolved default.", resolved_as: "0% digital service tax assumed." },
      ],
      sample_inputs: { product_count: 60, project_template_name: "E-Commerce Build" },
    },
    leadSimulation: {
      lead_id: "lead_rosewood_03",
      source: "email",
      received_at: "Sept 3, 2026, 4:20 PM ET",
      sender_name: "Elena Vance",
      sender_title: "Founder",
      sender_company: "Rosewood Home Goods",
      raw_message: "Hi! We're Rosewood Home Goods, we sell home decor and want to finally start selling online — probably around 60 products to start. We don't have anyone who can write product descriptions well, so it'd be great if you could handle that too, and if you could also just make sure the basic SEO stuff is set up since we have zero idea how to do that ourselves. No rush on timeline, just want it done properly.",
      extracted_params: {
        products_count: 60,
        tier_requested: "E-Commerce Build",
        addons_requested: ["Copywriting", "Basic SEO Setup"],
        client_state: "Remote",
      },
      tailored_sales_copy: {
        executive_overview: "Rosewood Home Goods is launching a curated online home decor boutique with ~60 products. Fieldstone Studio will deliver a high-converting, mobile-responsive Shopify/headless store with professional product copywriting and SEO foundations.",
        deliverables_scope: "• Custom E-Commerce Store Build (up to 100 product catalog capacity)\n• Professional Product Copywriting (60 product descriptions + category copy)\n• Technical Search Engine Optimization Foundations & Analytics Setup\n• 4–6 Week Guaranteed Launch Timeline",
        guarantee_and_sla: "Structured 50/50 payment milestone schedule with staging preview sign-off prior to final payment.",
      },
    },
    receipt: {
      receipt_id: "REC-FSS-2026-1045",
      proposal_id: "PROP-FSS-7721",
      date_issued: "September 7, 2026",
      valid_until: "October 1, 2026",
      status: "verified",
      company: {
        name: "Fieldstone Studio",
        location: "Remote (US-based)",
        email: "studio@fieldstonestudio.com",
        phone: "(800) 555-0182",
      },
      client: {
        name: "Elena Vance",
        company: "Rosewood Home Goods",
        location: "Remote",
        email: "elena@rosewoodhome.com",
      },
      deal_summary: {
        tier_name: "E-Commerce Build Template",
        products_count: 60,
        payment_terms: "50% Kickoff Deposit / 50% Final Delivery",
      },
      line_items: [
        { id: "li_1", label: "E-Commerce Build Base Template (up to 100 products)", amount: 9500, type: "package" },
        { id: "li_2", label: "Add-on: Professional Copywriting (60 SKUs)", amount: 600, type: "addon" },
        { id: "li_3", label: "Add-on: Basic SEO Architecture Setup", amount: 450, type: "addon" },
        { id: "li_4", label: "10% Stackable Add-on Bundle Discount", amount: -105, type: "discount", isDiscount: true },
      ],
      financials: {
        base_subtotal: 9500,
        discounts_total: 105,
        taxable_subtotal: 10445,
        tax_rate: 0,
        tax_amount: 0,
        grand_total: 10445,
        formatted_grand_total: "$10,445.00",
      },
      payment_milestones: [
        { milestone_name: "Milestone 1: Kickoff Deposit (50%)", trigger_description: "Due upon proposal agreement and discovery kickoff", share_percentage: 50, amount: 5222.5, status: "pending" },
        { milestone_name: "Milestone 2: Final Launch Payment (50%)", trigger_description: "Due upon staging sign-off and domain launch", share_percentage: 50, amount: 5222.5, status: "pending" },
      ],
      governing_rules: [
        "60 products within 100-product cap of E-Commerce Build",
        "2 stackable add-ons selected → 10% discount applied to add-on subtotal ($1,050.00 × 10% = -$105.00)",
        "50/50 payment milestone split applied ($5,222.50 deposit / $5,222.50 launch)",
      ],
    },
  },
};

